FROM docker.io/library/debian:trixie

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    openssh-server \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*