#!/bin/bash
set -e
if [ -n "${SSH_SERVING_USER}" ]; then
    if [ -n "${SSH_SERVING_SHELL}" ]; then
        CUR_SHELL=$(getent passwd ${SSH_SERVING_USER} | cut -d: -f7)
        if [ "${SSH_SERVING_SHELL}" != "${CUR_SHELL}" ]; then
            chsh -s "${SSH_SERVING_SHELL}" "${SSH_SERVING_USER}"
        fi
    fi
fi
exec /usr/sbin/sshd -D