# ================= 第一阶段：专门用来下载规则文件 =================
FROM alpine:latest AS downloader

RUN apk add --no-cache curl tar

WORKDIR /download

ENV CURL_OPTS="-L --retry 5 --retry-delay 3 --connect-timeout 15"

RUN curl ${CURL_OPTS} -o geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat \
    && curl ${CURL_OPTS} -o geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

RUN curl ${CURL_OPTS} -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip \
    && unzip xray.zip -d xray_dir

RUN V2RAYA_URL=$(curl -s https://api.github.com/repos/v2rayA/v2rayA/releases/latest | grep "browser_download_url.*v2raya_linux_x64" | head -n 1 | cut -d '"' -f 4) \
    && curl ${CURL_OPTS} -o v2raya ${V2RAYA_URL} \
    && chmod +x v2raya

RUN SINGBOX_URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "browser_download_url.*linux-amd64.tar.gz" | head -n 1 | cut -d '"' -f 4) \
    && curl ${CURL_OPTS} -o sing-box.tar.gz ${SINGBOX_URL} \
    && tar -zxvf sing-box.tar.gz \
    && mv sing-box-*-linux-amd64/sing-box . \
    && chmod +x sing-box

FROM alpine:latest

ARG TARGET_TZ=Asia/Shanghai

RUN apk update \
    && apk add --no-cache \
    ca-certificates \
    iptables \
    ip6tables \
    iproute2 \
    bash \
    tzdata \
    \
    && cp /usr/share/zoneinfo/${TARGET_TZ} /etc/localtime \
    && echo "${TARGET_TZ}" > /etc/timezone \
    && apk del tzdata

ENV V2RAYA_V2RAY_BIN=/usr/bin/xray
ENV V2RAYA_LOG_DIR=/var/log/v2raya
ENV XRAY_LOCATION_ASSET=/usr/share/xray

COPY --from=downloader /download/xray_dir/xray /usr/bin/xray
COPY --from=downloader /download/v2raya /usr/bin/v2raya
COPY --from=downloader /download/sing-box /usr/bin/sing-box
COPY --from=downloader /download/geoip.dat ${XRAY_LOCATION_ASSET}/geoip.dat
COPY --from=downloader /download/geosite.dat ${XRAY_LOCATION_ASSET}/geosite.dat

RUN mkdir -p ${V2RAYA_LOG_DIR}

EXPOSE 2017

CMD ["v2raya", "--address", "0.0.0.0:2017", "--log-disable-file"]