FROM docker.io/library/debian:trixie

ARG DEBIAN_FRONTEND=noninteractive
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  apt-transport-https \
  ca-certificates

RUN [ -f /etc/apt/sources.list ] && mv /etc/apt/sources.list /etc/apt/sources.list.bak || true
RUN mv /etc/apt/sources.list.d /etc/apt/sources.list.d.bak && \
  mkdir -p /etc/apt/sources.list.d
COPY ./files/tsinghua.sources /etc/apt/sources.list.d/tsinghua.sources
COPY --chown=root:root --chmod=644 ./files/microsoft.gpg /usr/share/keyrings/microsoft.gpg
COPY ./files/vscode.sources /etc/apt/sources.list.d/vscode.sources

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && apt-get install -y \
  openssh-server \
  build-essential \
  iproute2 \
  cmake \
  llvm-dev \
  clang \
  lldb \
  clang-tools \
  clang-format \
  python3-dev \
  python3-pip \
  python3-venv \
  rustup \
  \
  git \
  curl \
  vcsh \
  zsh \
  code \
  vim-nox \
  emacs \
  htop \
  \
  alacritty \
  kitty \
  rxvt-unicode \
  tmux

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get install -y \
  locales \
  rsync \
  swig \
  libgmp-dev \
  libmpfr-dev \
  m4

RUN sed -i -E \
  -e 's/# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' \
  -e 's/# *zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/g' \
  /etc/locale.gen && \
  echo 'LANG="en_US.UTF-8"' >> /etc/locale.conf && \
  locale-gen

RUN ln -sf bash /bin/sh

RUN mkdir -p /var/run/sshd
RUN ssh-keygen -A
RUN sed -E -i \
  -e 's/# *PubkeyAuthentication (yes|no)/PubkeyAuthentication yes/g' \
  -e 's/# *X11Forwarding (yes|no)/X11Forwarding yes/g' \
  -e 's/# *UseDNS (yes|no)/UseDNS no/g' \
  -e 's/# *PermitTTY (yes|no)/PermitTTY yes/g' \
  /etc/ssh/sshd_config

# annoying file permission checking
RUN sed -E -i \
  -e 's/# *StrictModes (yes|no)/StrictModes no/g' \
  /etc/ssh/sshd_config

# Set a root password
# RUN echo 'root:<password>' | chpasswd
# Permit root login over SSH
# RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# Fix for PAM (Pluggable Authentication Modules) issues in some environments
# RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

# Expose the SSH port
EXPOSE 22
# Start sshd in the foreground (-D) to keep the container running
# CMD ["/usr/sbin/sshd", "-D"]
COPY ./setup-ssh-user.py /setup-ssh-user.py
COPY ./start-ssh-server.py /start-ssh-server.py
COPY ./entrypoint.sh /entrypoint.sh
ENV SSH_SERVING_UID=
ENV SSH_SERVING_USER=
ENV SSH_SERVING_SHELL=
# COPY ./ssh-login-hook.sh /ssh-login-hook.sh
# RUN echo "session optional pam_exec.so seteuid /ssh-login-hook.sh" >> /etc/pam.d/sshd
ENTRYPOINT [ "/entrypoint.sh" ]